server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jwt
    username: root
    password: 123123
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
